apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-hs-mern 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-hs-mern-revanth
  template:
    metadata:
      labels:
        app: backend-hs-mern-revanth
    spec:
      containers:
      - name: profile-microservice
        image: asia-southeast1-docker.pkg.dev/academic-notch-413206/profile/profile:latest
        ports:
        - containerPort: 3002
        env:
        - name: MONGO_URL
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_URL
---
apiVersion: v1
kind: Service
metadata:
  name: profileservice-be-service
spec:
  selector:
    app: backend-hs-mern-revanth
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002
  type: LoadBalancer
